default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/db.sqlite3

test:
  primary:
    <<: *default
    database: db/db.sqlite3

production:
  primary:
    <<: *default
    database: db/db.sqlite3